version: '3.8'

services:
  web:
    build: .
    command: gunicorn translate_and_qr_codes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./translate_and_qr_codes:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
